# Environment, used in ssm paths etc.
# dev|prod
environment: <<specifyEnvironment>>

# Name of the k3s cluster. 
# Note: this is a not the actual name of the cluster within ArgoCD since it runs just a single server (name=default)
# It will be propagated to apps and used e.g. in ingress host names
clusterName: <<specifyClusterName>>

# Domain used for internal ingress
internalDomain: internal.tbnl.nl

# Domain used for externel (cloudflare tunnel)
externalDomain: <<specifyExternalDomain>>

# GitOps revision to track
targetRevision: main