apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gpm
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.externalSecrets.secretName }}"
    creationPolicy: Owner
  data:
  - secretKey: secretKey
    remoteRef:
      key: /tbnl-tf/{{ .Values.externalSecrets.environment }}/cluster-secret/gpm
