apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    targetRevision: __TARGET_REVISION__
    helm:
      values: |
        environment: __ENVIRONMENT__
        name: __NAME__
        clusterName: __CLUSTER_NAME__
        targetRevision: __TARGET_REVISION__
        externalDomain: __EXTERNAL_DOMAIN__
      valueFiles:
      - values-__ENVIRONMENT__.yaml
      - values-__NAME__.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
