apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
    template:
      data:
        credentials.json: |-
          {{ data.config }}    
  data:
  - secretKey: config
    remoteRef:
      key: /tbnl-tf/prod/cluster-secret/cloudflare-tunnel
      version: "2"
