apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |-
          {{ "{{ .config }}" }}
{{ with index .Values.externalSecrets.configurations .Values.externalSecrets.cluster }}
  data:
  - secretKey: config
    remoteRef:
      key: {{ .key }}
      version: {{ .version }}
{{ end }}