apiVersion: v2
name: cloudflare-tunnel
version: 0.0.1
description: "Setup Cloudflare Tunnel"

dependencies:
  - name: cloudflare-tunnel
    repository: https://cloudflare.github.io/helm-charts
    version: 0.3.0