cloudflare-tunnel:
  # https://github.com/cloudflare/helm-charts/blob/main/charts/cloudflare-tunnel/values.yaml
  cloudflare:
    tunnelName: <<specifyThis>>
    secretName: tunnel-credentials
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '2000'

externalSecrets:
  # Define ssm paths and versions to use for a given cluster
  #
  # Note: We can't just pass in the cluster name, since the actual version differs per cluster.
  # Using this mapping forces us to give an existing cluster name, of which the exact path and version will follow.
  configurations:
    dev-blue:
      key: /tbnl-tf/dev/cluster-secret/cloudflare-tunnel/dev-blue
      version: "1"
    dev-green:
      key: /tbnl-tf/dev/cluster-secret/cloudflare-tunnel/dev-green
      version: "1"
    prod-blue:
      key: /tbnl-tf/prod/cluster-secret/cloudflare-tunnel/prod-blue
      version: "1"
    prod-green:
      key: /tbnl-tf/prod/cluster-secret/cloudflare-tunnel/prod-green
      version: "1"
  # This defines which of the above configurations to use
  cluster: <<specifyThis>>
