apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newrelic-license
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: newrelic-license
    creationPolicy: Owner
  data:
  - secretKey: license-key
    remoteRef:
      key: /tbnl-tf/{{ .Values.externalSecrets.environment }}/cluster-secret/newrelic_license_key
