apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: default
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: example
    creationPolicy: Owner
  data:
  - secretKey: key1
    remoteRef:
      key: /tbnl-tf/{{ .Values.externalSecrets.environment }}/cluster-secret/example/{{ .Values.externalSecrets.cluster }}
      # version: "1"
