apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: honeycomb
  namespace: honeycomb
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: honeycomb
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: /tbnl-tf/{{ .Values.externalSecrets.environment }}/cluster-secret/honeycomb_api_key
