apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps-kustomization
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - application: argocd
      - application: traefik-addons
  template:
    metadata:
      name: '{{application}}'
      namespace: argocd
      annotations:
        domain/internal: '{{metadata.annotations.domain/internal}}'
    spec:
      source:
        repoURL: https://github.com/tbeijen/tbnl-gitops.git
        path: 'applications/{{application}}'
        targetRevision: main
        kustomize:
          commonAnnotations:
            domain/internal: '{{metadata.annotations.domain/internal}}'
      project: default
      destination:
        server: https://kubernetes.default.svc
