apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: kube-system
  annotations:
    parameters/domain-internal: 'traefik.placeholder-domain.internal'
spec:
  ingressClassName: traefik
  rules:
    - host: will-be-set-by-replacement-from-annotation
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-dashboard
                port:
                  number: 9000