apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- helmchartconfig.yaml
- ingress.yaml
- service.yaml

replacements:
- source:
    fieldPath: metadata.annotations.parameters/domain-internal
    kind: Ingress
    name: traefik-ingress
  targets:
  - fieldPaths:
    - spec.rules.0.host
    options:
      create: true
    select:
      kind: Ingress
      name: traefik-ingress
