apiVersion: v1
kind: Secret
metadata:
  name: github-tbnl-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/tbeijen/tbnl-gitops.git
