apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    parameters/domain-internal: 'argocd.placeholder-domain.internal'
spec:
  ingressClassName: traefik
  rules:
  - host: will-be-set-by-replacement-from-annotation
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
