apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
# https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.9/manifests/install.yaml
- install.yaml
- ingress.yaml
- github.repository.yaml
- bouncer.yaml

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
      - server.disable.auth=true
  - name: argocd-cm
    behavior: merge
    literals: 
      - timeout.reconciliation=70s

replacements:
- source:
    fieldPath: metadata.annotations.parameters/domain-internal
    kind: Ingress
    name: argocd-server-ingress
  targets:
  - fieldPaths:
    - spec.rules.0.host
    options:
      create: true
    select:
      kind: Ingress
      name: argocd-server-ingress

patchesStrategicMerge:
# First merging the notifications catalog 'as is', then merging the slack service on top
# https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.9/notifications_catalog/install.yaml
- notifications-cm.yaml
- notifications-cm.patch.yaml