apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
# https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.4/manifests/install.yaml
- install.yaml
- ingress.yaml
- github.repository.yaml

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
      - server.disable.auth=true
  - name: argocd-cm
    behavior: merge
    literals:
      - timeout.reconciliation=60s
