apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
  - secretKey: slack-token
    remoteRef:
      key: /tbnl-tf/dev/cluster-secret/argocd_notifications_slack_token
