apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token
  # Only want notification when something actually changed
  # See: https://github.com/argoproj/argo-cd/issues/12169#issuecomment-1699422153
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit (customized).
      oncePer: app.status.sync.revision
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() < 2
