# https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml
k8s-monitoring:
  cluster:
    name: <<specifyCluster>>


externalSecrets:
  environment: <<specifyEnvironment>>
