# This overlay exists to set the internal domain value to match the server/cluster name
# This works for limited set of clusters, but will be hard to maintain quickly
#
# This overlay exists as demo. For now we directly apply the base, 
# replacing the ${NAME} placeholder with the actual name using sed.
#
# @TODO Investigate: Name argocd cluster according to server (cli possible?), 
# then use cluster-generator to bootstrap cluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

commonAnnotations: 
  domain/internal: demo.internal.tbnl.nl
