apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/argocd
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    targetRevision: "{{ .Values.targetRevision }}"
    kustomize:
      commonAnnotations:
        parameters/domain-internal: "argocd.{{ .Values.clusterName }}.{{ .Values.internalDomain}}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
