apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: applications/cloudflare-tunnel
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    targetRevision: "{{ .Values.targetRevision }}"
    helm:
      valuesObject:
        cloudflare-tunnel:
          cloudflare:
            tunnelName: tbnl-{{ .Values.clusterName }}
            ingress:
            - hostname: podinfo.{{ .Values.externalDomain }}
              service: http://podinfo.podinfo.svc:9898
        externalSecrets:
          cluster: "{{ .Values.clusterName }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
