apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: default
  source:
    path: applications/eso
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    targetRevision: "{{ .Values.targetRevision }}"
    helm:
      valuesObject:
        externalSecrets:
          environment: "{{ .Values.environment }}"
          cluster: "{{ .Values.clusterName }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
