apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  project: default
  source:
    path: applications/gatekeeper
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    targetRevision: "{{ .Values.targetRevision }}"
    helm:
      valuesObject:
        externalSecrets:
          environment: "{{ .Values.environment }}"
        gatekeeper-policy-manager:
          ingress:
            enabled: true
            hosts:
            - host: gpm.{{ .Values.clusterName }}.{{ .Values.internalDomain}}
              paths:
              - "/"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
