apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-constraints
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/gatekeeper-constraints
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    targetRevision: "{{ .Values.targetRevision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
