apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  project: default
  source:
    path: applications/grafana-k8s-monitoring
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    targetRevision: "{{ .Values.targetRevision }}"
    helm:
      # valueFiles:
      # - values-dev.yaml
      valuesObject:
        k8s-monitoring:
          cluster:
            name: "{{ .Values.clusterName }}"
          externalServices:
            prometheus:
              host: https://prometheus-prod-24-prod-eu-west-2.grafana.net
              basicAuth:
                username: "1421777"
                passwordKey: api-key
              secret:
                create: false
                name: grafana-cloud
                # namespace: ""
            loki:
              host: https://logs-prod-012.grafana.net
              basicAuth:
                username: "809879"
                passwordKey: api-key
              secret:
                create: false
                name: grafana-cloud
            tempo:
              host: https://tempo-prod-10-prod-eu-west-2.grafana.net:443
              basicAuth:
                username: "807313"
                passwordKey: api-key
              secret:
                create: false
                name: grafana-cloud
            metrics:
              enabled: true
              cost:
                enabled: false
              node-exporter:
                enabled: true
            logs:
              enabled: true
              pod_logs:
                enabled: true
              cluster_events:
                enabled: true
            traces:
              # enabled: true
              enabled: false
            opencost:
              enabled: false
            kube-state-metrics:
              # enabled: true
              enabled: false
            prometheus-node-exporter:
              enabled: true
            prometheus-operator-crds:
              enabled: true
            grafana-agent: {}
            grafana-agent-logs: {}
        externalSecrets:
          environment: "{{ .Values.environment }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
