{{- if .Values.apps.newrelic.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newrelic
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: newrelic
  project: default
  source:
    path: applications/newrelic
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    targetRevision: "{{ .Values.targetRevision }}"
    helm:
      valuesObject:
        externalSecrets:
          environment: "{{ .Values.environment }}"
        nri-bundle:
          global:
            cluster: "{{ .Values.clusterName }}" 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
