apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo
  project: default
  source:
    chart: podinfo
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: "6.5.2"
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: "podinfo.{{ .Values.clusterName }}.{{ .Values.internalDomain}}"
              paths:
                - path: /
                  pathType: ImplementationSpecific
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
