apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-addons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/traefik-addons
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    kustomize:
      patches:
      - patch: |-
          - op: replace
            path: "/spec/rules/0/host"
            value: traefik.{{ .Values.clusterName }}.{{ .Values.internalDomain }}
  syncPolicy:
    automated:
      prune: true
      # selfHeal: true


