apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-addons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/traefik-addons
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    kustomize:
      commonAnnotations:
        parameters/domain-internal: "traefik.{{ .Values.clusterName }}.{{ .Values.internalDomain}}"
    # Note:
    # a kustomize block containing 'patches' seems not supported.
    # Worse: It causes the parent app-of-apps to always get out-of-sync by rendering 
    # this kustomization in the parent manifest actual state (probably a bug)
    #
    # kustomize:
    #   patches:
    #   - patch: |-
    #       - op: replace
    #         path: "/spec/rules/0/host"
    #         value: traefik.{{ .Values.clusterName }}.{{ .Values.internalDomain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


