apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/argocd
    repoURL: https://github.com/tbeijen/tbnl-gitops.git
    kustomize:
      commonAnnotations:
        domain/internal: '{{metadata.annotations.domain/internal}}'
        domain/external: '{{metadata.annotations.domain/external}}'
  syncPolicy:
    automated:
      prune: true
